'use client'
// import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./../globals.css";
import PageMode from "@/components/[dark-light]M/pageMode";
import ToastProvider from "@/context/toastContext/toastContext";
import { ConvexClientProvider } from "@/app/ConvexClientProvider";
import Navbar from "@/components/NaveBar/navbar";
import CustomizedSnackbars from "@/components/toast/toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
    <body>
    <ToastProvider>
      <PageMode>


  <ConvexClientProvider>
    <Navbar/>
    {children}
    </ConvexClientProvider>
  
   
  </PageMode>        
  <CustomizedSnackbars/>
    </ToastProvider>
    
    </body>
    
    

    </html>
  );
}
